
server:
  port: 8763
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${srping.application.name}:${server.port}-user
    prefer-ip-address: true
feign:
  httpclient:
    connection-timeout: 3000
ribbon:
  eureka:
    enabled: true